### ISSUE TITLE
nodejs无法调用onekey-connnet

### ISSUE THREAD

**Issue by itoukaijiE** [OneKeyHQ/electrum#691]
在node中使用onekey-connet和trezor-connet，示例代码如下:
```
import TrezorConnect from 'trezor-connect';
// import TrezorConnect from '@onekeyhq/connect';

(async () => {
    await TrezorConnect.init({
            connectSrc: 'https://localhost:8088/',
            lazyLoad: true, // this param will prevent iframe injection until TrezorConnect.method will be called
            manifest: {
                email: 'developer@xyz.com',
                appUrl: 'http://your.application.com',
            },
            webusb: false
        });

    let res = await TrezorConnect.ethereumGetAddress({
        path: "m/44'/60'/0'/0/0"
    });
    console.log(res);

})();
```
在使用不同版本的包的时候输出不同。

当使用`@onekeyhq/8.1.25-extended`时，输出
```
{
  success: false,
  payload: { error: 'window is not defined', code: undefined }
}
```
可见onekey-connet必须在浏览器中使用。

当使用`trezor-connect/8.1.25`时，输出
```
(node:70314) UnhandledPromiseRejectionWarning: Error: This version of trezor-connect is not suitable to work without browser. Use trezor-connect@extended package instead
    at Object.TypedError (/Users/hyg/Programme/yarntest/node_modules/trezor-connect/lib/constants/errors.js:103:10)
    at empty (/Users/hyg/Programme/yarntest/node_modules/trezor-connect/lib/env/node/index.js:13:27)
    at Object.init (/Users/hyg/Programme/yarntest/node_modules/trezor-connect/lib/index.js:38:27)
    at /Users/hyg/Programme/yarntest/onekey.ts:5:25
    at step (/Users/hyg/Programme/yarntest/onekey.ts:33:23)
    at Object.next (/Users/hyg/Programme/yarntest/onekey.ts:14:53)
    at /Users/hyg/Programme/yarntest/onekey.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/hyg/Programme/yarntest/onekey.ts:4:12)
    at /Users/hyg/Programme/yarntest/onekey.ts:4:2
(Use `node --trace-warnings ...` to show where the warning was created)
(node:70314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```
该版本提示
```
Error: This version of trezor-connect is not suitable to work without browser. Use trezor-connect@extended package instead
```
说明要用extended包。

当使用`trezor-connect/8.1.25-extended`时，输出
```
{
  id: 1,
  success: false,
  payload: { error: 'Transport is missing', code: 'Transport_Missing' }
}
```
我手边没有trezor，所以无法验证能成功，但显然该报错说明确实其实现逻辑与onekey-connet不同。

根据[trezor.js](https://github.com/trezor/trezor.js)的说明，可以被Nodejs集成，而这部分代码被合并到了trezor-connect中。
此外，直接在nodejs中调用trezor-connet的项目也有[cardano-hw-cli](https://github.com/vacuumlabs/cardano-hw-cli)

**Comment by kwoktung** [comment]
https://github.com/trezor/connect/blob/4cd54ebfafbf9a4247581772fc02c75cba87c22b/src/js/device/DeviceList.js#L55

**Comment by itoukaijiE** [comment]
@kwoktung 确实bridge是必须的，不过看起来onekey-connect报的错和有没有bridge无关，因为nodejs的环境中没有window对象，所以报window undefined的错本身就是一个bug？

**Comment by loatheb** [comment]
@itoukaijiE 可以更新下依赖到 v8.1.26 或者 v8.1.26-extended 两个版本重试下，修复了 node.js 环境报错。

`$(version)` 和 `${version}-extended` 两个模块都是打包成的 CommonJS 模块化规范，所以都是能直接在 node.js 用的，区别应该就是 extended 会多一些额外配置，比如当前最新官方固件版本，bridge 的二进制文件等等，细节可以自己编译试下。

同时写了个简单的 node.js demo，https://github.com/OneKeyHQ/connect/tree/onekey/examples/node 。

你的例子和上面这个 demo 我本地 node.js v14.16.0 都能正常运行。

**Comment by itoukaijiE** [comment]
https://github.com/OneKeyHQ/connect/tree/onekey/examples/node 这个例子和上面那个demo在输出完毕之后都没有退出程序，而是hang住了？

**Comment by loatheb** [comment]
@itoukaijiE 算是吧，他有个 listen bridge 返回的  stream，类似于服务器一样

**Comment by loatheb** [comment]
node.js 调用问题已修复，使用 v8.1.26 & v8.1.26-extended 之后版本即可，issue 先关闭了，后续有问题可以继续重新开。
